# shellcheck shell=bash
CONFIG_DIR="$HOME/dotfiles"

# :: environment variables

__prompt() {
    local prevexit="$?"
    local blackbg="\[\e[40m\]"
    local redfg="\[\e[31m\]"
    local bluefg="\[\e[34m\]"
    local greenfg="\[\e[1;32m\]"
    local endcolor="\[\e[0m\]"

    PS1="$blackbg"
    # diff color if the previous command failed
    if [ $prevexit -ne 0 ]; then
        PS1+="$redfg[$prevexit]\W/"
    else
        PS1+="$bluefg\W/"
    fi
    # show git branch
    if git rev-parse --git-dir &>/dev/null; then
        PS1+=" $greenfg::$(git branch --show-current):: "
    fi
    PS1+="$ $endcolor "
}
PROMPT_COMMAND=__prompt

export EDITOR="emacsclient -t"
export VISUAL="emacsclient -t"

eval "$(/opt/homebrew/bin/brew shellenv)"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

export GOPATH=$(go env GOPATH)
export PATH="$PATH:$GOPATH/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # 
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export LSP_USE_PLISTS=true # improve lsp-mode perf
export BASH_SILENCE_DEPRECATION_WARNING=1 # mute deprecation warning

# :: aliases

alias cdp="pushd"
alias cdl="dirs -v"
alias cdr="dirs -c"
alias e='${EDITOR}'
alias ls="ls --color=always"
alias lsa="ls -a"
alias lsl="ls -al"
alias src="source ~/.bash_profile"

alias brain="e $HOME/.brain.org"
alias erc="e $CONFIG_DIR/emacs/init.el"
alias shrc="e $CONFIG_DIR/bash/bash_profile"
alias shbs="e $CONFIG_DIR/bash/bootstrap.sh"
alias tmrc="e $CONFIG_DIR/tmux/tmux.conf"

alias gb="git branch"
alias gbc="git checkout -b"
alias gc="git checkout"
alias gd="git diff"
alias gm="git merge"
alias gp="git pull --ff-only"
alias gs="git status"

alias tek="tmux kill-server"
alias tun="tmux new-session -As main"

alias rek="killall emacs"
alias run="emacs --daemon"
alias er="rek;run"

# :: startup
if [ -z "$TMUX" ]; then
    tun
fi
