# shellcheck shell=bash
CONFIG_DIR="$HOME/develop/dotfiles"
SANDBOX="$HOME/develop/sandbox"

# :: environment variables

__prompt() {
    local prevexit="$?"
    local blackbg="\[\e[40m\]"
    local redfg="\[\e[31m\]"
    local bluefg="\[\e[34m\]"
    local greenfg="\[\e[1;32m\]"
    local endcolor="\[\e[0m\]"

    PS1="$blackbg"
    # diff color if the previous command failed
    if [ $prevexit -ne 0 ]; then
        PS1+="$redfg[$prevexit] \W/"
    else
        PS1+="$bluefg\W/"
    fi
    # show git branch
    if git rev-parse --git-dir &>/dev/null; then
        PS1+=" $greenfg::$(git branch --show-current):: "
    fi
    PS1+="$ $endcolor "
}
PROMPT_COMMAND=__prompt

export EDITOR="emacsclient -t"
export VISUAL="emacsclient -t"

eval "$(/opt/homebrew/bin/brew shellenv)"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

export GOPATH=$(go env GOPATH)
export PATH="$PATH:$GOPATH/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  #
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export LSP_USE_PLISTS=true # improve lsp-mode perf
export BASH_SILENCE_DEPRECATION_WARNING=1 # mute deprecation warning

# :: aliases

alias e='${EDITOR}'
alias ls="ls --color=always --group-directories-first -I Desktop -I Documents -I Downloads -I Library -I Movies -I Music -I Pictures -I Public"
alias lsa="ls -A"
alias src="source ~/.bash_profile"

alias erc="e $CONFIG_DIR/emacs/init.el"
alias shrc="e $CONFIG_DIR/bash/bash_profile"
alias shbs="e $CONFIG_DIR/bash/bootstrap.sh"
alias tmrc="e $CONFIG_DIR/tmux/tmux.conf"
alias brain="e $HOME/.brain.org"

alias gb="git branch"
alias gbc="git checkout -b"
alias gc="git checkout"
alias gd="git diff"
alias gm="git merge"
alias gp="git pull --ff-only"
alias gs="git status"

alias tmk="tmux kill-server"
alias tmr="tmux new-session -As main"

alias ek="killall emacs"
alias er="emacs --daemon"

alias gomt="go mod tidy"
alias gocl="go clean -modcache"
alias sgo="e $SANDBOX/main.go"
