# shellcheck shell=bash
CONFIG_DIR="$HOME/develop/dotfiles"
SANDBOX="$HOME/sandbox"

# :: environment variables

function git_dirty {
  [ -n "$(git status -s 2>/dev/null)" ]
}
__prompt() {
    local prevexit="$?"
    local blackbg="\[\e[40m\]"
    local redfg="\[\e[31m\]"
    local greenfg="\[\e[32m\]"
    local yellowfg="\[\e[33m\]"
    local bluefg="\[\e[34m\]"
    local endcolor="\[\e[0m\]"

    PS1="$blackbg"
    # diff color if the previous command failed
    if [ $prevexit -ne 0 ]; then
        PS1+="${redfg}[$prevexit] \W/"
    else
        PS1+="$bluefg\W/"
    fi
    # show branch, and if it's dirty
    if git rev-parse --git-dir &>/dev/null; then
        if git_dirty; then
            PS1+=" $yellowfg"
        else
            PS1+=" $greenfg"
        fi
        PS1+="$(git branch --show-current) "
    fi
    PS1+="$endcolor "
    history -a
}
PROMPT_COMMAND=__prompt

export EDITOR="emacs"
export VISUAL="emacs"
export HISTSIZE=2000
shopt -s histappend

eval "$(/opt/homebrew/bin/brew shellenv)"
export MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

export GOPATH=$(go env GOPATH)
export PATH="$PATH:$GOPATH/bin"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  #
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export FZF_DEFAULT_COMMAND="fd"
export LSP_USE_PLISTS=true # improve lsp-mode perf
export BASH_SILENCE_DEPRECATION_WARNING=1 # mute deprecation warning

# :: aliases

alias dev="cd \$(fd --type d -d 1 . ~/develop/ | fzf)"
alias e='${EDITOR}'
alias f="fzf"
alias ie='e $(fzf)'
alias icd='cd $(fzf)'
alias ls="ls --color=always --group-directories-first -I Desktop -I Documents -I Downloads -I Library -I Movies -I Music -I Pictures -I Public"
alias lsa="ls -A"
alias src="source ~/.bash_profile"
alias ctop="grep -Ev '^ls|^ctop' \$HISTFILE | sort | uniq -c | sort -n"
alias erc="e $CONFIG_DIR/emacs/init.el"
alias shrc="e $CONFIG_DIR/bash/bash_profile"
alias shbs="e $CONFIG_DIR/bash/bootstrap.sh"
alias tmrc="e $CONFIG_DIR/tmux/tmux.conf"
alias brain="e \$HOME/.brain.org"

alias gb="git branch"
alias gbc="git checkout -b"
alias gc="git checkout"
alias gd="git diff"
alias gm="git merge"
alias gp="git pull --ff-only"
alias gs="git status"

alias er="emacs --daemon"
alias ec="emacsclient -t"

alias tmk="tmux kill-server"
alias tmr="tmux new-session -As main"

alias gomt="go mod tidy"
alias gocl="go clean -modcache"
alias sgo="e $SANDBOX/main.go"

# docker
alias drc="docker exec -it"
alias ddf="docker system df"
## pruning
alias dcche="yes | docker builder prune -a"
alias dcimg="yes | docker image prune -a"
alias dccnt="yes | docker container prune"
## remove
alias drcnt="docker rm -f"
alias drimg="docker image rm"
alias dstop="docker ps -q | xargs docker rm -f"
## listing
alias dlimg="docker images"
alias dlcnt="docker ps -a --format \"table {{.Names}}\t{{.Image}}\t{{.Ports}}\t{{.Status}}\t{{.State}}\t{{.Mounts}}\t{{.Networks}}\""
alias dscnt="docker ps --format \"table {{.Names}}\t{{.Image}}\""
